# Generated by Django 4.0.4 on 2022-04-15 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.CharField(max_length=255)),
                ('contenuto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Risposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('commento', models.TextField()),
                ('titolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risposta', to='forum.forum')),
            ],
        ),
    ]
