# Generated by Django 4.0.4 on 2022-04-15 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manage', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='fornitore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manage.owner'),
        ),
        migrations.AddField(
            model_name='forum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manage.cliente'),
        ),
    ]
