# Generated by Django 4.0.4 on 2022-04-15 11:30

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Prodotti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dimensione', models.CharField(default=None, max_length=255)),
                ('tipo_materiale', models.CharField(default=None, max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('review', models.TextField(default='Hello')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=200)),
                ('comment_body', models.TextField()),
                ('rating_fornitore', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('rating_prodotto', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='products.prodotti')),
            ],
        ),
    ]
