# Generated by Django 4.0.3 on 2022-03-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    #questo file mim serve come corrispondenza su quello che scrivo su file models e quello che trovo su DB
    #L'effettiva scrittura avviene quando do alla fine il comando migrate

    operations = [
        migrations.CreateModel(
            name='Prodotti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.TextField()),
            ],
        ),
    ]
