# Generated by Django 4.0.4 on 2022-04-13 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manage', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manage.cliente'),
        ),
        migrations.AddField(
            model_name='prodotti',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoria'),
        ),
        migrations.AddField(
            model_name='prodotti',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prodotti', to='user_manage.owner'),
        ),
    ]
