# Generated by Django 4.0.3 on 2022-03-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotti',
            name='review',
            field=models.TextField(default='Hello'),
        ),
    ]
