# Generated by Django 4.0.4 on 2022-06-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotti',
            name='review',
        ),
    ]
