# Generated by Django 4.0.3 on 2022-04-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=200)),
                ('comment_body', models.TextField()),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='products.prodotti')),
            ],
        ),
    ]
