# Generated by Django 4.0.3 on 2022-04-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_fornitore',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rating_prodotto',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
    ]
