# Generated by Django 4.0.3 on 2022-04-09 09:26

from django.db import migrations
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review_rating_fornitore_review_rating_prodotto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating_fornitore',
            field=products.models.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating_prodotto',
            field=products.models.IntegerRangeField(),
        ),
    ]
